$script = <<-'SCRIPT'
timedatectl set-timezone Asia/Tokyo
dnf -y remove open-vm-tools
dnf -y update
dnf install -y curl policycoreutils openssh-server openssh-clients
systemctl enable sshd
systemctl start sshd
firewall-cmd --permanent --add-service=http
firewall-cmd --permanent --add-service=https
systemctl reload firewalld
dnf install postfix
systemctl enable postfix
systemctl start postfix
curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh | bash
EXTERNAL_URL="https://gitlab.local" dnf install -y gitlab-ce
SCRIPT

Vagrant.configure("2") do |config|
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end
  config.vm.define :centos8 do |centos8|
    centos8.vm.box = "centos/8"
    centos8.vm.network "public_network", mac: "000d58000001", ip: "192.168.1.151"
    centos8.vm.hostname = "gitlab.local"
    centos8.vm.provider "virtualbox" do |vb|
      vb.name = "gitlab"
      vb.memory = "16384"
      vb.cpus = 4
    end
    centos8.vm.provision "shell", inline: $script
  end
end
